kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - name: helloapp
          image: eu.gcr.io/awesome-project/hello-app:v1
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
